bindep: install openssl-devel
e.g: https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_periodic-1hr/github.com/ansible-collections/vmware/master/ansible-test-cloud-integration-vcenter_1esxi_with_nested-python36/ac21d3e/job-output.html

```
   creating build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6
   gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o -Wconversion -Wno-error=sign-conversion
   build/temp.linux-x86_64-3.6/_openssl.c:546:10: fatal error: openssl/opensslv.h: No such file or directory
         ^~~~~~~~~~~~~~~~~~~~
   compilation terminated.
   error: command 'gcc' failed with exit status 1
```