Make network-ee-sanity-tests non-voting (#1262)
Make network-ee-sanity-tests non-voting

Signed-off-by: GomathiselviS gomathiselvi@gmail.com
Due to failures in ansible/ansible , making  network-ee-sanity-tests non-voting
Failure:
ERROR: Found 1 import issue(s) on python 3.8 which need to be resolved:
2021-12-07 04:35:51.249863 | centos-8-stream | ERROR: plugins/action/deepsec_intrusion_prevention_rules.py:0:0: stderr: [WARNING]: packaging Python module unavailable; unable to validate collection
2021-12-07 04:35:51.249938 | centos-8-stream | See documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/import.html

Reviewed-by: None <None>