Revert "add the possibility to define extra tests for ansible-test-splitter (#1662)" (#1669)
Revert "add the possibility to define extra tests for ansible-test-splitter (#1662)"

There is actually a problem with #1662. Thanks Mark Chappell.
2022-11-03 14:51:05.154291 | TASK [ansible-test-splitter : Split up the workload]
2022-11-03 14:51:08.745115 | controller | Traceback (most recent call last):
2022-11-03 14:51:08.745463 | controller |   File "/tmp/list_changed_targets.py", line 470, in <module>
2022-11-03 14:51:08.745498 | controller |     pr_request = read_pullrequest_zuul_override(
2022-11-03 14:51:08.745510 | controller |   File "/tmp/list_changed_targets.py", line 445, in read_pullrequest_zuul_override
2022-11-03 14:51:08.745523 | controller |     desc = read_pullrequest_body(project_name, pull_request)
2022-11-03 14:51:08.745534 | controller |   File "/tmp/list_changed_targets.py", line 435, in read_pullrequest_body
2022-11-03 14:51:08.745663 | controller |     return [x for x in requests.get(change_url).json().get("body").split("\n") if x]
2022-11-03 14:51:08.745682 | controller | AttributeError: 'NoneType' object has no attribute 'split'
2022-11-03 14:51:09.036429 | controller | ERROR
2022-11-03 14:51:09.036580 | controller | {
2022-11-03 14:51:09.036615 | controller |   "delta": "0:00:01.521214",
2022-11-03 14:51:09.036642 | controller |   "end": "2022-11-03 14:51:08.764549",
2022-11-03 14:51:09.036666 | controller |   "msg": "non-zero return code",
2022-11-03 14:51:09.036690 | controller |   "rc": 1,
2022-11-03 14:51:09.036713 | controller |   "start": "2022-11-03 14:51:07.243335"
2022-11-03 14:51:09.036736 | controller | }
2022-11-03 14:51:09.047045 |

This reverts commit 45caf41.